### PR TITLE
Fix error msg and file descriptor number. Also fish support.

### PR DESCRIPTION
**Pull request by afaikiac**
Thank you very much for your plugin! I made some fixes and refactored the code a bit. I hope you'll find it useful.

### CODE REVIEW

**Comment by vy** [comment]
Thanks for the kind words and contribution @afaikiac! I have found the new version of `copyq.bash` bloated with comments, but hey, this is the first PR! I will buy it.

One minor question: The title of the PR is _"Fix error msg and file descriptor number"_, yet it appears to me like a simple Fish support. Am I missing something?

**Comment by afaikiac** [comment]
Thanks for the tip, I tried to fix it. `die()` is only in Perl, as I know. And I fixed some file descriptors to remove unnecessary output. Previously the script was returning "true" after 45 sec. 

I decided to add fish support later. I should have done it in different branches and made two pull requests. But I thought about it too late. If you want, I can do properly.

**Comment by vy** [comment]
@afaikiac, nope, here `die` is provided by the `pass` itself. (Extension gets `source`d into the `pass` script while getting executed.)

**Comment by afaikiac** [comment]
Yes, indeed, found it in the [sources](https://git.zx2c4.com/password-store/tree/src/password-store.sh#n55). Thank you for accepting my PRs :)

**Comment by vy** [comment]
My pleasure! :bowing_man: Keep up the good job and spirit! :muscle:

**Pull request closed without merging**
